sudo: false
language: cpp
cache:
  ccache: true
  directories:
  - "/home/travis/toolchain"

matrix:
  include:

  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libboost1.55-all-dev
        - libssl-dev
        - g++-8
        - gcc-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LABEL="linux-gcc-8"
    - _DEPLOYABLE="true"
    - STRIP="strip"

  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libboost1.55-all-dev
        - libssl-dev
        - g++-7
        - gcc-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LABEL="linux-gcc-7"
    - _DEPLOYABLE="true"
    - STRIP="strip"

  - os: osx
    osx_image: xcode10
    compiler: gcc
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LABEL="osx-g++-8"
    - STRIP="strip"

  - os: osx
    osx_image: xcode10
    compiler: gcc
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LABEL="osx-g++-7"
    - STRIP="strip"

  - os: osx
    osx_image: xcode10
    compiler: clang
    env:
    - MATRIX_EVAL="CC=/usr/local/opt/llvm/bin/clang && CXX=/usr/local/opt/llvm/bin/clang++"
    - LABEL="osx"
    - _DEPLOYABLE="true"
    - STRIP="strip"

  - os: linux
    env:
    - MATRIX_EVAL="CC=aarch64-linux-gnu-gcc && CXX=aarch64-linux-gnu-g++"
    - LABEL="aarch64"
    - _DEPLOYABLE="true"
    - STRIP="aarch64-linux-gnu-strip"

before_install:
- eval $MATRIX_EVAL

install:
- if [[ "${LABEL:0:3}" == "osx" ]]; then brew cask uninstall --force oclint || true
  ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install llvm || travis_retry
  brew upgrade llvm ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install openssl || travis_retry
  brew upgrade openssl ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then brew link --force openssl ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then ln -s /usr/local/opt/openssl/include/openssl
  /usr/local/include ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install ccache ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"
  ; fi
- if [[ "$LABEL" == "osx-g++-8" ]]; then travis_retry brew install gcc@8 ; fi
- if [[ "$LABEL" == "osx-g++-7" ]]; then travis_retry brew install gcc@7 ; fi

script:
- eval $MATRIX_EVAL
- if [[ "$LABEL" == "aarch64" ]]; then source scripts/prep-aarch64.sh ; fi
- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=Release -DSTATIC=true ..
- make -j2
- if [[ "$LABEL" != "aarch64" ]]; then ./src/cryptotest ; fi

before_deploy:
- if [[ "${TRAVIS_TAG}" == "" ]]; then export TRAVIS_TAG=${TRAVIS_COMMIT} ; fi
- cd src
- TARGETS="kegcoind kegwallet kegwallet-beta kegcoin-service kegminer cryptotest wallet-api"
- "${STRIP} ${TARGETS}"
- rm -rf KegcoinGold-${TRAVIS_TAG}
- mkdir KegcoinGold-${TRAVIS_TAG}
- cp ${TARGETS} KegcoinGold-${TRAVIS_TAG}/
- cp ../../LICENSE KegcoinGold-${TRAVIS_TAG}/
- tar -zcvf KegcoinGold-${TRAVIS_TAG}-${LABEL}.tar.gz KegcoinGold-${TRAVIS_TAG}/
- rm -rf builds
- mkdir builds
- cp KegcoinGold-${TRAVIS_TAG}-${LABEL}.tar.gz builds

deploy:
  provider: releases
  api_key:
    secure: sPobaxx1zELYYvNretuJFywZN4aw8ZVO1CcyrYy5ZZTMIBNwhKWR7qCLltZvBT3bgbPeUDuRuVCa1++Mbcv8Py9/x/BndRy7NUwh2pX5RV/6swP8D/MZDptsrO1EVHcti7RoMqyksEeLliECAZ9HHiOdO3qEqrbnwVL6bIDaKZUcevxMc7M8lWiQETS7X3B4eWrAW0DrHC6Xn0f2tOC6jekp6PLK/y6kJQvzGNC4VeWkYgFKR5xz3K8u/HWn3vmyua5qE7yfCXV8Os4++IzTfPSByTs334GT23x1aWul8pYrONyLXbk2MklQK8ursC6trW1bEK/3v6QZswQeE6HPyvsZ7FPlhz2X9AT6N7brVWXrTRR/nmeJSs8ZAJBtD6ScAspM/3KVbfEp6M2W88Dz9tsNDE/ch/u3wk4G3FhPYbEOlHtGDYzc1T6FapHhX+JI0/+ZZ8UNIYet/4wSwMo9vVpct3J6Iy0dtldca8gFLAEVMIEWGJctZE4XGRG675SgYKE7Iu3bFgF3H/HpXKqDmc+pLUYz4Q4hu+fo9B5i+fo93yL8aqK07VwsbHwoefX+hfoZtJNGYV7uizr/B8rZPfv6Oeg1RcLZ6/lA3MkIOosjMFRK2yOUqN3YGgV8CEozPfzTFZz2KfZnhNh4ezS57q03i8TXu6/sOFSL0gfdEz4=
  file:
    - KegcoinGold-${TRAVIS_TAG}-${LABEL}.tar.gz
  skip_cleanup: true
  on:
    repo: kegcoin-project/kegcoin-gold
    tags: true
    condition: "$_DEPLOYABLE = true"
